on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install UI Deps
      run: npm ci
    - name: Fake Install flux
      run: mkdir -p pkg/flux/bin && touch pkg/flux/bin/flux
    - name: Build UI Assets
      run: make cmd/gitops/ui/run/dist/index.html
    - name: Check Format
      run: make check-format
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42.1
        args: --timeout=600s
        skip-go-installation: true

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Clean
      run: make clean
    - name: build
      run: make gitops
    - name: Store gitops binaries
      uses: actions/upload-artifact@v2
      with:
          name: gitops-binaries
          path: bin
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install lcov
      run:  sudo apt-get install -y lcov
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install UI Deps
      run: npm ci
    # - name: NPM Audit
    #   run: npm audit
    - name: Build UI Assets
      run: make cmd/gitops/ui/run/dist/main.js
    - name: Set up kubebuilder
      uses: fluxcd/pkg/actions/kubebuilder@main
    - name: Set up flux dir but let dependencies install flux
      run: mkdir -p pkg/flux/bin && tools/download-deps.sh $PWD/tools/dependencies.toml
    - name: Unit Tests with Coverage
      run: make coverage/merged.lcov
      env:
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: merged.lcov

  smoke-tests:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 60
    env:
        GITHUB_ORG: weaveworks-gitops-test
        GITHUB_TOKEN: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_TOKEN }}"
        GITHUB_KEY: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_SSH_KEY }}"
        ARTIFACTS_BASE_DIR: "/tmp/wego-test"
        IS_TEST_ENV: "true"
        GITLAB_ORG: weave-gitops
        GITLAB_SUBGROUP: weabe-gitops-sub
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup selenium standalone server
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo apt-get install -y google-chrome-stable

        wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver

        mkdir -p cmd/selenium
        cd cmd/selenium
        wget  https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar
        mv selenium-server-standalone-3.14.0.jar selenium-server-standalone.jar

        xvfb-run -a --server-args="-screen 0 1280x1024x24" java -jar ./selenium-server-standalone.jar &
        cd -
    - name: Setup Kubernetes
      uses: engineerd/setup-kind@v0.5.0
      with:
        name: "${{ format('katc-{0}', github.run_id) }}"
        version: "v0.11.0"
        image: kindest/node:v1.20.7
        config: "./test/acceptance/test/configs/kind-config.yaml"
    - name: Kind-check
      run: |
        kubectl get pods -A
    - name: Download gitops binaries
      uses: actions/download-artifact@v2
      with:
        name: gitops-binaries
        path: bin
    - name: Change bin permissions
      run: |
        chmod +x bin/gitops
        ls -la bin
    - name: Download dependecies
      run: |
        make dependencies
    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_SSH_KEY }}
    - name: Configure git settings
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "weave-test-user@example.com"
        git config --global user.name "Testy McTestFace"
        git config --global url.ssh://git@github.com/.insteadOf https://github.com/
    - name: Run smoke tests from acceptance suite
      run: |
        export WEGO_BIN_PATH=$(pwd)/bin/gitops
        export CLUSTER_PROVIDER=kubectl
        export DELETE_WEGO_RUNTIME_ON_EACH_TEST=true
        go get github.com/onsi/ginkgo/ginkgo
        go get github.com/onsi/gomega
        ginkgo --focus=SmokeTest --randomizeSuites --reportFile=${{ env. ARTIFACTS_BASE_DIR }}/smoke-test-results.xml -v ./test/acceptance/test/...
    - name: Store smoke test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: smoke-test-artifacts
        path: ${{ env. ARTIFACTS_BASE_DIR }}
        retention-days: 1

  acceptance-tests:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    timeout-minutes: 90
    env:
        GITHUB_ORG: weaveworks-gitops-test
        GITHUB_TOKEN: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_TOKEN }}"
        GITHUB_KEY: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_SSH_KEY }}"
        ARTIFACTS_BASE_DIR: "/tmp/wego-test"
        IS_TEST_ENV: "true"
        GITLAB_ORG: weave-gitops
        GITLAB_SUBGROUP: weabe-gitops-sub
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup selenium standalone server
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        sudo apt-get install -y google-chrome-stable

        wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver

        mkdir -p cmd/selenium
        cd cmd/selenium
        wget  https://selenium-release.storage.googleapis.com/3.14/selenium-server-standalone-3.14.0.jar
        mv selenium-server-standalone-3.14.0.jar selenium-server-standalone.jar

        xvfb-run -a --server-args="-screen 0 1280x1024x24" java -jar ./selenium-server-standalone.jar &
        cd -
    - name: Setup Kubernetes
      uses: engineerd/setup-kind@v0.5.0
      with:
        name: "${{ format('katc-{0}', github.run_id) }}"
        version: "v0.11.0"
        image: kindest/node:v1.20.7
        config: "./test/acceptance/test/configs/kind-config.yaml"
    - name: Kind-check
      run: |
        kubectl get pods -A
    - name: Download gitops binaries
      uses: actions/download-artifact@v2
      with:
        name: gitops-binaries
        path: bin
    - name: Change bin permissions
      run: |
        chmod +x bin/gitops
        ls -la bin
    - name: Download dependecies
      run: |
        make dependencies
    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_SSH_KEY }}
    - name: Configure git settings
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "weave-test-user@example.com"
        git config --global user.name "Testy McTestFace"
        git config --global url.ssh://git@github.com/.insteadOf https://github.com/
    - name: Run Full Acceptance Suite
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        export WEGO_BIN_PATH=$(pwd)/bin/gitops
        export CLUSTER_PROVIDER=kubectl
        go get github.com/onsi/ginkgo/ginkgo
        go get github.com/onsi/gomega/...
        ginkgo --randomizeSuites --reportFile=${{ env. ARTIFACTS_BASE_DIR }}/acceptance-test-results.xml -v ./test/acceptance/test/...
    - name: Store acceptance test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: acceptance-test-artifacts
        path: ${{ env.ARTIFACTS_BASE_DIR }}
        retention-days: 1
  library-integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
      - name: Run Library Integration Test
        env:
          GITHUB_TOKEN: "${{ secrets.github_token }}"
        run: make lib-test
